# -*- coding: utf-8 -*-
"""Task 2c.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e2USepnA0idqMNTQ5U5oj8cgU5R1Mbu-
"""

class Node:
    def __init__(self,e,n):
        self.elem=e
        self.next=n
n1=Node(10,None)
head=n1
n2=Node(20,None)
n3=Node(30,None)
n4=Node(40,None)
n1.next=n2
n2.next=n3
n3.next=n4

def printList(h):
    if h.next==None:
        print(h.elem)
    else:
            printList(h.next)
            print(h.elem)
printList(head)