# -*- coding: utf-8 -*-
"""Task 2a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e2USepnA0idqMNTQ5U5oj8cgU5R1Mbu-
"""

def binary(n):
    if n == 0:
        return
    else:
        binary(n//2)
        print(n%2,end='')
n=int(input())
binary(n)