# -*- coding: utf-8 -*-
"""Task 1c.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e2USepnA0idqMNTQ5U5oj8cgU5R1Mbu-
"""

def printArray(arr,idx=0):
    if idx==len(arr):
        return
    else:
        print(arr[idx],end=',')
        printArray(arr,idx+1)
printArray([1,2,3,4,5])