# -*- coding: utf-8 -*-
"""Task 1a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e2USepnA0idqMNTQ5U5oj8cgU5R1Mbu-
"""

def factorial(n):
    if n==1:
        return 1
    else:
        return n*factorial(n-1)
n=int(input())
factorial(n)