# -*- coding: utf-8 -*-
"""Task 4a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e2USepnA0idqMNTQ5U5oj8cgU5R1Mbu-
"""

def line(n):
 if n==0:
    return
 else:
     line(n-1)
     print(n,end=' ')

def pattern(n):
    if n==0:
        return
    else:
        pattern(n-1)
        line(n)
        print()
n=int(input())
pattern(n)