# -*- coding: utf-8 -*-
"""Task 4b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e2USepnA0idqMNTQ5U5oj8cgU5R1Mbu-
"""

def line(n):
    if (n == 0):
        return
    print(n, end =" ")
    line(n - 1)

def space(n):
    if (n == 0):
        return
    print(" ", end=" ")
    space(n - 1)



def pattern(n, x):
    if (n == 0):
        return
    space(n - 1)
    line(x - n + 1)
    print()
    pattern(n - 1, x)

pattern(5,5)