# -*- coding: utf-8 -*-
"""Task 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e2USepnA0idqMNTQ5U5oj8cgU5R1Mbu-
"""

vowels='AEIOU'
consonants='BCDFGHJKLMNPQRSTVWXYZ'
class hashing:
    def __init__(self,arr,size=9):
        self.arr=arr
        self.size=size
        self.new_arr=[0]*size


    def hash(self,st):
            c_no=0
            sum=0
            for i in st:
                if i in consonants:
                    c_no+=1
                elif (i not in consonants) and (i not in vowels):
                    sum+=int(i)
            key_idx=((c_no*24)+sum) % 9
            return key_idx


    def hashtable(self):
            for j in range(len(self.arr)):
                idx=self.hash(self.arr[j])
                while self.new_arr[idx]!=0:
                    idx=(j+idx)%len(self.new_arr)
                self.new_arr[idx]=self.arr[j]
            return self.new_arr



arr=['ST1E89B8A32','ABXYZ345J','DT37','JURF08968T','AHF34OJ','FUDHP213','53HUD','HDUF23','HUF98E']
h=hashing(arr)
h.hashtable()