# -*- coding: utf-8 -*-
"""Task 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e2USepnA0idqMNTQ5U5oj8cgU5R1Mbu-
"""

class  KeyIndex:
    def __init__(self,arr):
        self.min=arr[0]
        for m in arr:
            if self.min>m:
                self.min=m

        if self.min<0:
            x=self.min
            x=x*(-1)
            max=arr[0]
            for mx in arr:
              if max<mx:
                max=mx
            self.aux_arr=[0]*(x+max+1)
            for i in range(len(arr)):
                idx=arr[i]+x
                self.aux_arr[idx]=self.aux_arr[idx]+1
            print(self.aux_arr)
        else:
            max=arr[0]
            for mx in arr:
              if max<mx:
                max=mx
            self.aux_arr=[0]*(max+1)
            for i in range(len(arr)):
                idx=arr[i]
                self.aux_arr[idx]=self.aux_arr[idx]+1
            print(self.aux_arr)


    def searching(self,x):
        if self.min<0:
            item=x+self.min
            if self.aux_arr[item]!=0:
                return True
            else:
                return False
        else:
            if self.aux_arr[x]!=0:
                return True
            else:
                return False

    def sort(self):
     if self.min>0:
      sum=0
      for i in range(len(self.aux_arr)):
        if self.aux_arr[i]!=0:
          sum+=self.aux_arr[i]
      sorted_arr=[0]*sum
      x=0
      for j in range(len(self.aux_arr)):
        if self.aux_arr[j]!=0:
          for k in range(self.aux_arr[j]):
            sorted_arr[x]=j
            x+=1
      return sorted_arr

     else:
      sum=0
      for i in range(len(self.aux_arr)):
        if self.aux_arr[i] != 0:
          sum +=self.aux_arr[i]
      sorted_arr=[0]*sum
      i = 0
      for j in range(len(self.aux_arr)):
        if self.aux_arr[j]!= 0:
          for k in range(self.aux_arr[j]):
            sorted_arr[i] = j - (self.min *(-1))
            i+=1
     return sorted_arr




a1= KeyIndex([4,2,3,-4,7,4])
a2= KeyIndex([4,2,3,4,7,4])
print(a1.searching(4))
print(a2.searching(1))
print(a1.sort())
print(a2.sort())