# -*- coding: utf-8 -*-
"""Task 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e2USepnA0idqMNTQ5U5oj8cgU5R1Mbu-
"""

def buildHouse(height):
    if height==0:
        return 'Can not build a house at all'
    elif height==1:
        return 8
    else:
        return 5+buildHouse(height-1)
height=int(input())
buildHouse(height)